# Generated by Django 4.1.5 on 2023-01-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='room name', max_length=64, verbose_name='name')),
                ('private', models.BooleanField(default=True, help_text='room privacy', verbose_name='private')),
                ('readers', models.ForeignKey(help_text='room readers', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='readers')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(help_text='message content', max_length=500, verbose_name='content')),
                ('status', models.BooleanField(default=False, help_text='read message status', verbose_name='status')),
                ('author', models.ForeignKey(help_text='message author', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('room', models.ForeignKey(help_text='discussion room', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
