# Generated by Django 4.1.5 on 2023-01-18 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='readers',
        ),
        migrations.AddField(
            model_name='room',
            name='readers',
            field=models.ManyToManyField(help_text='room readers', to=settings.AUTH_USER_MODEL, verbose_name='readers'),
        ),
    ]
